version: '2'
services:
  web:
    image: vmelnych/odoo:13.0613
    container_name: odoo
    restart: always
    depends_on:
      - db
    ports:
      - "80:8069"
    volumes:
      - c:/docker_storage/odoo/lib:/var/lib/odoo
      - c:/docker_storage/odoo/etc:/etc/odoo
      - c:/docker_storage/odoo/opt:/opt/odoo
      - c:/docker_storage/odoo/addons:/mnt/extra-addons
      - c:/docker_storage/odoo/log:/var/log/odoo
  db:
    image: postgres:12.1
    container_name: postgredb
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - PGDATA=/var/lib/postgresql/data/pgdata
      - FETCH_OCA_DEPENDENCIES=True
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_PASSWORD
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 6001:80

volumes:
    pgdata:
      driver: local
    pgadmin:
      driver: local